
import { Surah } from './types';

// Password for application access control
export const APP_PASSWORD = '081234';

// Complete 114 Surah list with starting pages for a standard 604-page Mushaf
export const SURAHS: Surah[] = [
  { number: 1, name: "Al-Faatiha", englishName: "Al-Faatiha", englishNameTranslation: "The Opening", numberOfAyahs: 7, revelationType: "Meccan", startPage: 1 },
  { number: 2, name: "Al-Baqara", englishName: "Al-Baqara", englishNameTranslation: "The Cow", numberOfAyahs: 286, revelationType: "Medinan", startPage: 2 },
  { number: 3, name: "Aal-i-Imraan", englishName: "Aal-i-Imraan", englishNameTranslation: "The Family of Imraan", numberOfAyahs: 200, revelationType: "Medinan", startPage: 50 },
  { number: 4, name: "An-Nisaa", englishName: "An-Nisaa", englishNameTranslation: "The Women", numberOfAyahs: 176, revelationType: "Medinan", startPage: 77 },
  { number: 5, name: "Al-Maaida", englishName: "Al-Maaida", englishNameTranslation: "The Table Spread", numberOfAyahs: 120, revelationType: "Medinan", startPage: 106 },
  { number: 6, name: "Al-An'aam", englishName: "Al-An'aam", englishNameTranslation: "The Cattle", numberOfAyahs: 165, revelationType: "Meccan", startPage: 128 },
  { number: 7, name: "Al-A'raaf", englishName: "Al-A'raaf", englishNameTranslation: "The Heights", numberOfAyahs: 206, revelationType: "Meccan", startPage: 151 },
  { number: 8, name: "Al-Anfaal", englishName: "Al-Anfaal", englishNameTranslation: "The Spoils of War", numberOfAyahs: 75, revelationType: "Medinan", startPage: 177 },
  { number: 9, name: "At-Tawba", englishName: "At-Tawba", englishNameTranslation: "The Repentance", numberOfAyahs: 129, revelationType: "Medinan", startPage: 187 },
  { number: 10, name: "Yunus", englishName: "Yunus", englishNameTranslation: "Jonah", numberOfAyahs: 109, revelationType: "Meccan", startPage: 208 },
  { number: 11, name: "Hud", englishName: "Hud", englishNameTranslation: "Hud", numberOfAyahs: 123, revelationType: "Meccan", startPage: 221 },
  { number: 12, name: "Yusuf", englishName: "Yusuf", englishNameTranslation: "Joseph", numberOfAyahs: 111, revelationType: "Meccan", startPage: 235 },
  { number: 13, name: "Ar-Ra'd", englishName: "Ar-Ra'd", englishNameTranslation: "The Thunder", numberOfAyahs: 43, revelationType: "Medinan", startPage: 249 },
  { number: 14, name: "Ibrahim", englishName: "Ibrahim", englishNameTranslation: "Abraham", numberOfAyahs: 52, revelationType: "Meccan", startPage: 255 },
  { number: 15, name: "Al-Hijr", englishName: "Al-Hijr", englishNameTranslation: "The Rocky Tract", numberOfAyahs: 99, revelationType: "Meccan", startPage: 262 },
  { number: 16, name: "An-Nahl", englishName: "An-Nahl", englishNameTranslation: "The Bee", numberOfAyahs: 128, revelationType: "Meccan", startPage: 267 },
  { number: 17, name: "Al-Israa", englishName: "Al-Israa", englishNameTranslation: "The Night Journey", numberOfAyahs: 111, revelationType: "Meccan", startPage: 282 },
  { number: 18, name: "Al-Kahf", englishName: "Al-Kahf", englishNameTranslation: "The Cave", numberOfAyahs: 110, revelationType: "Meccan", startPage: 293 },
  { number: 19, name: "Maryam", englishName: "Maryam", englishNameTranslation: "Mary", numberOfAyahs: 98, revelationType: "Meccan", startPage: 305 },
  { number: 20, name: "Ta-Ha", englishName: "Ta-Ha", englishNameTranslation: "Ta-Ha", numberOfAyahs: 135, revelationType: "Meccan", startPage: 312 },
  { number: 21, name: "Al-Anbiyaa", englishName: "Al-Anbiyaa", englishNameTranslation: "The Prophets", numberOfAyahs: 112, revelationType: "Meccan", startPage: 322 },
  { number: 22, name: "Al-Hajj", englishName: "Al-Hajj", englishNameTranslation: "The Pilgrimage", numberOfAyahs: 78, revelationType: "Medinan", startPage: 332 },
  { number: 23, name: "Al-Mu'minoon", englishName: "Al-Mu'minoon", englishNameTranslation: "The Believers", numberOfAyahs: 118, revelationType: "Meccan", startPage: 342 },
  { number: 24, name: "An-Noor", englishName: "An-Noor", englishNameTranslation: "The Light", numberOfAyahs: 64, revelationType: "Medinan", startPage: 350 },
  { number: 25, name: "Al-Furqaan", englishName: "Al-Furqaan", englishNameTranslation: "The Criterion", numberOfAyahs: 77, revelationType: "Meccan", startPage: 359 },
  { number: 26, name: "Ash-Shu'araa", englishName: "Ash-Shu'araa", englishNameTranslation: "The Poets", numberOfAyahs: 227, revelationType: "Meccan", startPage: 367 },
  { number: 27, name: "An-Naml", englishName: "An-Naml", englishNameTranslation: "The Ant", numberOfAyahs: 93, revelationType: "Meccan", startPage: 377 },
  { number: 28, name: "Al-Qasas", englishName: "Al-Qasas", englishNameTranslation: "The Stories", numberOfAyahs: 88, revelationType: "Meccan", startPage: 385 },
  { number: 29, name: "Al-'Ankaboot", englishName: "Al-'Ankaboot", englishNameTranslation: "The Spider", numberOfAyahs: 69, revelationType: "Meccan", startPage: 396 },
  { number: 30, name: "Ar-Room", englishName: "Ar-Room", englishNameTranslation: "The Romans", numberOfAyahs: 60, revelationType: "Meccan", startPage: 404 },
  { number: 31, name: "Luqman", englishName: "Luqman", englishNameTranslation: "Luqman", numberOfAyahs: 34, revelationType: "Meccan", startPage: 411 },
  { number: 32, name: "As-Sajda", englishName: "As-Sajda", englishNameTranslation: "The Prostration", numberOfAyahs: 30, revelationType: "Meccan", startPage: 415 },
  { number: 33, name: "Al-Ahzaab", englishName: "Al-Ahzaab", englishNameTranslation: "The Combined Forces", numberOfAyahs: 73, revelationType: "Medinan", startPage: 418 },
  { number: 34, name: "Saba", englishName: "Saba", englishNameTranslation: "Sheba", numberOfAyahs: 54, revelationType: "Meccan", startPage: 428 },
  { number: 35, name: "Faatir", englishName: "Faatir", englishNameTranslation: "The Originator", numberOfAyahs: 45, revelationType: "Meccan", startPage: 434 },
  { number: 36, name: "Ya-Seen", englishName: "Ya-Seen", englishNameTranslation: "Ya-Seen", numberOfAyahs: 83, revelationType: "Meccan", startPage: 440 },
  { number: 37, name: "As-Saaffaat", englishName: "As-Saaffaat", englishNameTranslation: "Those who set the Ranks", numberOfAyahs: 182, revelationType: "Meccan", startPage: 446 },
  { number: 38, name: "Saad", englishName: "Saad", englishNameTranslation: "The Letter Saad", numberOfAyahs: 88, revelationType: "Meccan", startPage: 453 },
  { number: 39, name: "Az-Zumar", englishName: "Az-Zumar", englishNameTranslation: "The Troops", numberOfAyahs: 75, revelationType: "Meccan", startPage: 458 },
  { number: 40, name: "Ghafir", englishName: "Ghafir", englishNameTranslation: "The Forgiver", numberOfAyahs: 85, revelationType: "Meccan", startPage: 467 },
  { number: 41, name: "Fussilat", englishName: "Fussilat", englishNameTranslation: "Explained in Detail", numberOfAyahs: 54, revelationType: "Meccan", startPage: 477 },
  { number: 42, name: "Ash-Shura", englishName: "Ash-Shura", englishNameTranslation: "Consultation", numberOfAyahs: 53, revelationType: "Meccan", startPage: 483 },
  { number: 43, name: "Az-Zukhruf", englishName: "Az-Zukhruf", englishNameTranslation: "The Ornaments of Gold", numberOfAyahs: 89, revelationType: "Meccan", startPage: 489 },
  { number: 44, name: "Ad-Dukhaan", englishName: "Ad-Dukhaan", englishNameTranslation: "The Smoke", numberOfAyahs: 59, revelationType: "Meccan", startPage: 496 },
  { number: 45, name: "Al-Jaathiya", englishName: "Al-Jaathiya", englishNameTranslation: "The Crouching", numberOfAyahs: 37, revelationType: "Meccan", startPage: 499 },
  { number: 46, name: "Al-Ahqaaf", englishName: "Al-Ahqaaf", englishNameTranslation: "The Wind-Curved Sandhills", numberOfAyahs: 35, revelationType: "Meccan", startPage: 502 },
  { number: 47, name: "Muhammad", englishName: "Muhammad", englishNameTranslation: "Muhammad", numberOfAyahs: 38, revelationType: "Medinan", startPage: 507 },
  { number: 48, name: "Al-Fath", englishName: "Al-Fath", englishNameTranslation: "The Victory", numberOfAyahs: 29, revelationType: "Medinan", startPage: 511 },
  { number: 49, name: "Al-Hujuraat", englishName: "Al-Hujuraat", englishNameTranslation: "The Dwellings", numberOfAyahs: 18, revelationType: "Medinan", startPage: 515 },
  { number: 50, name: "Qaf", englishName: "Qaf", englishNameTranslation: "The Letter Qaf", numberOfAyahs: 45, revelationType: "Meccan", startPage: 518 },
  { number: 51, name: "Adh-Dhaariyat", englishName: "Adh-Dhaariyat", englishNameTranslation: "The Winnowing Winds", numberOfAyahs: 60, revelationType: "Meccan", startPage: 520 },
  { number: 52, name: "At-Tur", englishName: "At-Tur", englishNameTranslation: "The Mount", numberOfAyahs: 49, revelationType: "Meccan", startPage: 523 },
  { number: 53, name: "An-Najm", englishName: "An-Najm", englishNameTranslation: "The Star", numberOfAyahs: 62, revelationType: "Meccan", startPage: 526 },
  { number: 54, name: "Al-Qamar", englishName: "Al-Qamar", englishNameTranslation: "The Moon", numberOfAyahs: 55, revelationType: "Meccan", startPage: 528 },
  { number: 55, name: "Ar-Rahmaan", englishName: "Ar-Rahmaan", englishNameTranslation: "The Beneficent", numberOfAyahs: 78, revelationType: "Medinan", startPage: 531 },
  { number: 56, name: "Al-Waaqi'a", englishName: "Al-Waaqi'a", englishNameTranslation: "The Inevitable", numberOfAyahs: 96, revelationType: "Meccan", startPage: 534 },
  { number: 57, name: "Al-Hadid", englishName: "Al-Hadid", englishNameTranslation: "The Iron", numberOfAyahs: 29, revelationType: "Medinan", startPage: 537 },
  { number: 58, name: "Al-Mujaadila", englishName: "Al-Mujaadila", englishNameTranslation: "The Pleading Woman", numberOfAyahs: 22, revelationType: "Medinan", startPage: 542 },
  { number: 59, name: "Al-Hashr", englishName: "Al-Hashr", englishNameTranslation: "The Exile", numberOfAyahs: 24, revelationType: "Medinan", startPage: 545 },
  { number: 60, name: "Al-Mumtahina", englishName: "Al-Mumtahina", englishNameTranslation: "She that is to be examined", numberOfAyahs: 13, revelationType: "Medinan", startPage: 549 },
  { number: 61, name: "As-Saff", englishName: "As-Saff", englishNameTranslation: "The Ranks", numberOfAyahs: 14, revelationType: "Medinan", startPage: 551 },
  { number: 62, name: "Al-Jumu'a", englishName: "Al-Jumu'a", englishNameTranslation: "The Congregation, Friday", numberOfAyahs: 11, revelationType: "Medinan", startPage: 553 },
  { number: 63, name: "Al-Munaafiqoon", englishName: "Al-Munaafiqoon", englishNameTranslation: "The Hypocrites", numberOfAyahs: 11, revelationType: "Medinan", startPage: 554 },
  { number: 64, name: "At-Taghaabun", englishName: "At-Taghaabun", englishNameTranslation: "The Mutual Disillusion", numberOfAyahs: 18, revelationType: "Medinan", startPage: 556 },
  { number: 65, name: "At-Talaaq", englishName: "At-Talaaq", englishNameTranslation: "The Divorce", numberOfAyahs: 12, revelationType: "Medinan", startPage: 558 },
  { number: 66, name: "At-Tahrim", englishName: "At-Tahrim", englishNameTranslation: "The Prohibition", numberOfAyahs: 12, revelationType: "Medinan", startPage: 560 },
  { number: 67, name: "Al-Mulk", englishName: "Al-Mulk", englishNameTranslation: "The Sovereignty", numberOfAyahs: 30, revelationType: "Meccan", startPage: 562 },
  { number: 68, name: "Al-Qalam", englishName: "Al-Qalam", englishNameTranslation: "The Pen", numberOfAyahs: 52, revelationType: "Meccan", startPage: 564 },
  { number: 69, name: "Al-Haaqqa", englishName: "Al-Haaqqa", englishNameTranslation: "The Reality", numberOfAyahs: 52, revelationType: "Meccan", startPage: 566 },
  { number: 70, name: "Al-Ma'aarij", englishName: "Al-Ma'aarij", englishNameTranslation: "The Ascending Stairways", numberOfAyahs: 44, revelationType: "Meccan", startPage: 568 },
  { number: 71, name: "Nooh", englishName: "Nooh", englishNameTranslation: "Noah", numberOfAyahs: 28, revelationType: "Meccan", startPage: 570 },
  { number: 72, name: "Al-Jinn", englishName: "Al-Jinn", englishNameTranslation: "The Jinn", numberOfAyahs: 28, revelationType: "Meccan", startPage: 572 },
  { number: 73, name: "Al-Muzzammil", englishName: "Al-Muzzammil", englishNameTranslation: "The Enshrouded One", numberOfAyahs: 20, revelationType: "Meccan", startPage: 574 },
  { number: 74, name: "Al-Muddaththir", englishName: "Al-Muddaththir", englishNameTranslation: "The Cloaked One", numberOfAyahs: 56, revelationType: "Meccan", startPage: 575 },
  { number: 75, name: "Al-Qiyaama", englishName: "Al-Qiyaama", englishNameTranslation: "The Resurrection", numberOfAyahs: 40, revelationType: "Meccan", startPage: 577 },
  { number: 76, name: "Al-Insaan", englishName: "Al-Insaan", englishNameTranslation: "The Man", numberOfAyahs: 31, revelationType: "Medinan", startPage: 578 },
  { number: 77, name: "Al-Mursalaat", englishName: "Al-Mursalaat", englishNameTranslation: "The Emissaries", numberOfAyahs: 50, revelationType: "Meccan", startPage: 580 },
  { number: 78, name: "An-Naba", englishName: "An-Naba", englishNameTranslation: "The Tidings", numberOfAyahs: 40, revelationType: "Meccan", startPage: 582 },
  { number: 79, name: "An-Naazi'aat", englishName: "An-Naazi'aat", englishNameTranslation: "Those who drag forth", numberOfAyahs: 46, revelationType: "Meccan", startPage: 583 },
  { number: 80, name: "'Abasa", englishName: "'Abasa", englishNameTranslation: "He Frowned", numberOfAyahs: 42, revelationType: "Meccan", startPage: 585 },
  { number: 81, name: "At-Takwir", englishName: "At-Takwir", englishNameTranslation: "The Overthrowing", numberOfAyahs: 29, revelationType: "Meccan", startPage: 586 },
  { number: 82, name: "Al-Infitaar", englishName: "Al-Infitaar", englishNameTranslation: "The Cleaving", numberOfAyahs: 19, revelationType: "Meccan", startPage: 587 },
  { number: 83, name: "Al-Mutaffifeen", englishName: "Al-Mutaffifeen", englishNameTranslation: "The Defrauding", numberOfAyahs: 36, revelationType: "Meccan", startPage: 587 },
  { number: 84, name: "Al-Inshiqaaq", englishName: "Al-Inshiqaaq", englishNameTranslation: "The Sundering", numberOfAyahs: 25, revelationType: "Meccan", startPage: 589 },
  { number: 85, name: "Al-Burooj", englishName: "Al-Burooj", englishNameTranslation: "The Mansions of the Stars", numberOfAyahs: 22, revelationType: "Meccan", startPage: 590 },
  { number: 86, name: "At-Taariq", englishName: "At-Taariq", englishNameTranslation: "The Night-Comer", numberOfAyahs: 17, revelationType: "Meccan", startPage: 591 },
  { number: 87, name: "Al-A'la", englishName: "Al-A'la", englishNameTranslation: "The Most High", numberOfAyahs: 19, revelationType: "Meccan", startPage: 591 },
  { number: 88, name: "Al-Ghaashiya", englishName: "Al-Ghaashiya", englishNameTranslation: "The Overwhelming", numberOfAyahs: 26, revelationType: "Meccan", startPage: 592 },
  { number: 89, name: "Al-Fajr", englishName: "Al-Fajr", englishNameTranslation: "The Dawn", numberOfAyahs: 30, revelationType: "Meccan", startPage: 593 },
  { number: 90, name: "Al-Balad", englishName: "Al-Balad", englishNameTranslation: "The City", numberOfAyahs: 20, revelationType: "Meccan", startPage: 594 },
  { number: 91, name: "Ash-Shams", englishName: "Ash-Shams", englishNameTranslation: "The Sun", numberOfAyahs: 15, revelationType: "Meccan", startPage: 595 },
  { number: 92, name: "Al-Layl", englishName: "Al-Layl", englishNameTranslation: "The Night", numberOfAyahs: 21, revelationType: "Meccan", startPage: 595 },
  { number: 93, name: "Ad-Duhaa", englishName: "Ad-Duhaa", englishNameTranslation: "The Morning Hours", numberOfAyahs: 11, revelationType: "Meccan", startPage: 596 },
  { number: 94, name: "Ash-Sharh", englishName: "Ash-Sharh", englishNameTranslation: "The Relief", numberOfAyahs: 8, revelationType: "Meccan", startPage: 596 },
  { number: 95, name: "At-Tin", englishName: "At-Tin", englishNameTranslation: "The Fig", numberOfAyahs: 8, revelationType: "Meccan", startPage: 597 },
  { number: 96, name: "Al-'Alaq", englishName: "Al-'Alaq", englishNameTranslation: "The Clot", numberOfAyahs: 19, revelationType: "Meccan", startPage: 597 },
  { number: 97, name: "Al-Qadr", englishName: "Al-Qadr", englishNameTranslation: "The Power", numberOfAyahs: 5, revelationType: "Meccan", startPage: 598 },
  { number: 98, name: "Al-Bayyina", englishName: "Al-Bayyina", englishNameTranslation: "The Clear Proof", numberOfAyahs: 8, revelationType: "Medinan", startPage: 598 },
  { number: 99, name: "Az-Zalzala", englishName: "Az-Zalzala", englishNameTranslation: "The Earthquake", numberOfAyahs: 8, revelationType: "Medinan", startPage: 599 },
  { number: 100, name: "Al-'Aadiyaat", englishName: "Al-'Aadiyaat", englishNameTranslation: "The Courser", numberOfAyahs: 11, revelationType: "Meccan", startPage: 599 },
  { number: 101, name: "Al-Qaari'a", englishName: "Al-Qaari'a", englishNameTranslation: "The Calamity", numberOfAyahs: 11, revelationType: "Meccan", startPage: 600 },
  { number: 102, name: "At-Takaathur", englishName: "At-Takaathur", englishNameTranslation: "The Rivalry in world increase", numberOfAyahs: 8, revelationType: "Meccan", startPage: 600 },
  { number: 103, name: "Al-'Asr", englishName: "Al-'Asr", englishNameTranslation: "The Declining Day", numberOfAyahs: 3, revelationType: "Meccan", startPage: 601 },
  { number: 104, name: "Al-Humaza", englishName: "Al-Humaza", englishNameTranslation: "The Traducer", numberOfAyahs: 9, revelationType: "Meccan", startPage: 601 },
  { number: 105, name: "Al-Fil", englishName: "Al-Fil", englishNameTranslation: "The Elephant", numberOfAyahs: 5, revelationType: "Meccan", startPage: 601 },
  { number: 106, name: "Quraish", englishName: "Quraish", englishNameTranslation: "Quraish", numberOfAyahs: 4, revelationType: "Meccan", startPage: 602 },
  { number: 107, name: "Al-Maa'oon", englishName: "Al-Maa'oon", englishNameTranslation: "Small Kindnesses", numberOfAyahs: 7, revelationType: "Meccan", startPage: 602 },
  { number: 108, name: "Al-Kawthar", englishName: "Al-Kawthar", englishNameTranslation: "Abundance", numberOfAyahs: 3, revelationType: "Meccan", startPage: 602 },
  { number: 109, name: "Al-Kaafiroon", englishName: "Al-Kaafiroon", englishNameTranslation: "The Disbelievers", numberOfAyahs: 6, revelationType: "Meccan", startPage: 603 },
  { number: 110, name: "An-Nasr", englishName: "An-Nasr", englishNameTranslation: "The Divine Support", numberOfAyahs: 3, revelationType: "Medinan", startPage: 603 },
  { number: 111, name: "Al-Masad", englishName: "Al-Masad", englishNameTranslation: "The Palm Fiber", numberOfAyahs: 5, revelationType: "Meccan", startPage: 603 },
  { number: 112, name: "Al-Ikhlaas", englishName: "Al-Ikhlaas", englishNameTranslation: "The Sincerity", numberOfAyahs: 4, revelationType: "Meccan", startPage: 604 },
  { number: 113, name: "Al-Falaq", englishName: "Al-Falaq", englishNameTranslation: "The Daybreak", numberOfAyahs: 5, revelationType: "Meccan", startPage: 604 },
  { number: 114, name: "An-Naas", englishName: "An-Naas", englishNameTranslation: "Mankind", numberOfAyahs: 6, revelationType: "Meccan", startPage: 604 },
];

export const FONT_OPTIONS = [
  { name: 'Uthmanic Hafs', value: 'Uthmanic' },
  { name: 'Hanafi Nastaleeq', value: 'Hanafi' },
  { name: 'KFGQPC Nastaleeq', value: 'Nastaleeq' },
  { name: 'Indopak', value: 'Indopak' },
  { name: 'Digital Khatt V1', value: 'KhattV1' },
  { name: 'Digital Khatt V2', value: 'KhattV2' },
  { name: 'Me Quran', value: 'MeQuran' },
  { name: 'Quran Fonts V2', value: 'QuranV2' },
];
